# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17fd9386fa55a65fb90e7360a9c4bbd252001e919e8f9db391e1235a3d4ff2c96410a5ab3a4e651aad7068f7606bc967a941e8a3d8be9a565c84cef1b794f098

test:
  secret_key_base: dd2fcc9e9d559b3ad946d2b2f3789839cf5d5bbde7fb83bb9c4bf6b4290f787d0ca1bcbbefe725761183740741d75f16929c910f3c22f0042ff1fda8922771f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
